#!/usr/bin/env bash

set -e

ROOT=$(dirname "${BASH_SOURCE}")

exec docker run \
    -d \
    --name devbox \
    --hostname="$(hostname)" \
    --privileged \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    --group-add video \
    --group-add render \
    --ipc=host \
    --restart always \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /lib/modules:/lib/modules \
    -v /dev:/dev \
    -v /usr/share/ca-certificates:/usr/share/ca-certificates \
    -v /etc/ssl/certs:/etc/ssl/certs \
    --mount type=bind,source=/home/yuanying,target=/home/yuanying,bind-propagation=slave \
    --network v6net \
    --ip6 2405:6581:8580:310::153 \
    -w /home/yuanying \
    --add-host braque:192.168.1.131 \
    --add-host chirico:192.168.1.83 \
    --add-host ducump:192.168.1.135 \
    --add-host pablo:192.168.1.134 \
    --add-host pablo:192.168.1.134 \
    --add-host poissonnerie:192.168.1.151 \
    --add-host uribo:192.168.1.152 \
    --add-host simone:192.168.1.153 \
    registry.fraction.jp/yuanying/devbox-rocm
