#!/usr/bin/env bash

set -e

ROOT=$(dirname "${BASH_SOURCE}")

exec docker run \
    --rm \
    -d \
    --name devbox \
    --hostname="$(hostname)" \
    --privileged \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /lib/modules:/lib/modules \
    -v /dev:/dev \
    -v /usr/share/ca-certificates:/usr/share/ca-certificates \
    -v /etc/ssl/certs:/etc/ssl/certs \
    --mount type=bind,source=/home/yuanying,target=/home/yuanying,bind-propagation=slave \
    -w /home/yuanying \
    -p 8080:8080 \
    -p 9090:9090 \
    -p 3222:3222 \
    -p 60000-60010:60000-60010/udp \
    --add-host braque:192.168.1.131 \
    --add-host chirico:192.168.1.83 \
    --add-host ducump:192.168.1.135 \
    --add-host pablo:192.168.1.134 \
    --add-host pablo:192.168.1.134 \
    --add-host poissonnerie:192.168.1.151 \
    --add-host uribo:192.168.1.152 \
    --add-host simone:192.168.1.153 \
    registry.fraction.jp/yuanying/devbox-amd64
